### PR TITLE
Add option to control ellipsis #50

### PR DESCRIPTION
**Pull request by gresolio**

### CODE REVIEW

**Comment by toptensoftware** [comment]
Thanks for this however it doesn't cover all cases.  

The case you've handled is where a rich string is truncated exactly on a paragraph boundary.  It also needs to handle the case where the truncation happens mid paragraph.  Take a look at` CheckHeightConstraints` in `TextBlock.cs` for where it does this.

https://github.com/toptensoftware/RichTextKit/blob/master/Topten.RichTextKit/TextBlock.cs#L1978

To explain... a `TextBlock` is a single laid out paragraph.  A RichString is a list of TextBlocks.  When a height constraint is hit such that a previous paragraph fits, but the first line of the next paragraph doesn't, RichString goes back an appends the ellipsis to the prior paragraph.  When a paragraph crosses a height constraint it creates the ellipsis itself.

**Comment by gresolio** [comment]
Thanks for the explanation. I have added ```EllipsisEnabled``` to ```TextBlock```, now it should cover all the cases: [af2e30f](https://github.com/toptensoftware/RichTextKit/pull/51/commits/af2e30f90ed7c6392d2478087199722b1ee8163c).

**Comment by gresolio** [comment]
Is this [af2e30f](https://github.com/toptensoftware/RichTextKit/pull/51/commits/af2e30f90ed7c6392d2478087199722b1ee8163c) good enough?
Or do you have other suggestions for improvement?

**Comment by toptensoftware** [comment]
Thanks for that.. it looks good I think. I'll do some testing and merge it asap (but I have a couple of busy days ahead so bear with me).

**Pull request merged**
